//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace ROB1_lab
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button Solve;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RapidExecutionStatus rapidExecutionStatus1;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton1;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton2;
        
        private ABB.Robotics.Tps.Windows.Forms.RadioButton radioButton3;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph1;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph2;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.BarGraph barGraph3;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.Solve = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.rapidExecutionStatus1 = new ABB.Robotics.ScreenMaker.Windows.Forms.RapidExecutionStatus();
            this.radioButton1 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.radioButton2 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.radioButton3 = new ABB.Robotics.Tps.Windows.Forms.RadioButton();
            this.barGraph1 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.barGraph2 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.barGraph3 = new ABB.Robotics.Tps.Windows.Forms.BarGraph();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // Solve
            // 
            this.Solve.BackColor = System.Drawing.Color.White;
            this.Solve.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.Solve.ForeColor = System.Drawing.SystemColors.ControlText;
            this.Solve.Location = new System.Drawing.Point(483, 335);
            this.Solve.Name = "Solve";
            this.Solve.Size = new System.Drawing.Size(136, 42);
            this.Solve.Text = "Solve";
            this.Solve.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.Solve.Click += new System.EventHandler(this.Solve_Click);
            // 
            // led1
            // 
            this.led1.BackColor = System.Drawing.SystemColors.ControlLight;
            this.led1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "Data", "connected_to_server")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(77, 32);
            this.led1.Name = "led1";
            this.led1.OffValue = false;
            this.led1.OnValue = true;
            this.led1.Size = new System.Drawing.Size(160, 41);
            this.led1.Text = "Server Status";
            // 
            // rapidExecutionStatus1
            // 
            this.rapidExecutionStatus1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.rapidExecutionStatus1.Location = new System.Drawing.Point(27, 32);
            this.rapidExecutionStatus1.Name = "rapidExecutionStatus1";
            this.rapidExecutionStatus1.Size = new System.Drawing.Size(44, 41);
            // 
            // radioButton1
            // 
            this.radioButton1.BackColor = System.Drawing.SystemColors.ControlLight;
            this.radioButton1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.radioButton1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton1.Location = new System.Drawing.Point(483, 127);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new System.Drawing.Size(136, 41);
            this.radioButton1.Text = "Place on A";
            this.radioButton1.CheckedChanged += new System.EventHandler(this.radioButton1_CheckedChanged);
            // 
            // radioButton2
            // 
            this.radioButton2.BackColor = System.Drawing.SystemColors.ControlLight;
            this.radioButton2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.radioButton2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton2.Location = new System.Drawing.Point(483, 174);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.Size = new System.Drawing.Size(136, 41);
            this.radioButton2.Text = "Place on B";
            this.radioButton2.CheckedChanged += new System.EventHandler(this.radioButton2_CheckedChanged);
            // 
            // radioButton3
            // 
            this.radioButton3.BackColor = System.Drawing.SystemColors.ControlLight;
            this.radioButton3.Checked = true;
            this.radioButton3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.radioButton3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.radioButton3.Location = new System.Drawing.Point(483, 221);
            this.radioButton3.Name = "radioButton3";
            this.radioButton3.Size = new System.Drawing.Size(136, 41);
            this.radioButton3.Text = "Place on C";
            this.radioButton3.CheckedChanged += new System.EventHandler(this.radioButton3_CheckedChanged);
            // 
            // barGraph1
            // 
            this.barGraph1.BackColor = System.Drawing.SystemColors.ControlLight;
            this.barGraph1.BarColor = System.Drawing.Color.Purple;
            this.barGraph1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "Data", "n_pieces"), new ABB.Robotics.ScreenMaker.Windows.Forms.Index[] {
                                new ABB.Robotics.ScreenMaker.Windows.Forms.Index(1)}), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.barGraph1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph1.Location = new System.Drawing.Point(75, 305);
            this.barGraph1.Maximum = new decimal(new int[] {
                        5,
                        0,
                        0,
                        0});
            this.barGraph1.Name = "barGraph1";
            this.barGraph1.Size = new System.Drawing.Size(26, 72);
            this.barGraph1.Value = new decimal(new int[] {
                        0,
                        0,
                        0,
                        0});
            // 
            // barGraph2
            // 
            this.barGraph2.BackColor = System.Drawing.SystemColors.ControlLight;
            this.barGraph2.BarColor = System.Drawing.Color.Purple;
            this.barGraph2.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "Data", "n_pieces"), new ABB.Robotics.ScreenMaker.Windows.Forms.Index[] {
                                new ABB.Robotics.ScreenMaker.Windows.Forms.Index(2)}), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.barGraph2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph2.Location = new System.Drawing.Point(202, 305);
            this.barGraph2.Maximum = new decimal(new int[] {
                        5,
                        0,
                        0,
                        0});
            this.barGraph2.Name = "barGraph2";
            this.barGraph2.Size = new System.Drawing.Size(26, 72);
            this.barGraph2.Value = new decimal(new int[] {
                        5,
                        0,
                        0,
                        0});
            // 
            // barGraph3
            // 
            this.barGraph3.BackColor = System.Drawing.SystemColors.ControlLight;
            this.barGraph3.BarColor = System.Drawing.Color.Purple;
            this.barGraph3.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "Data", "n_pieces"), new ABB.Robotics.ScreenMaker.Windows.Forms.Index[] {
                                new ABB.Robotics.ScreenMaker.Windows.Forms.Index(3)}), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.barGraph3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.barGraph3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.barGraph3.Location = new System.Drawing.Point(386, 305);
            this.barGraph3.Maximum = new decimal(new int[] {
                        5,
                        0,
                        0,
                        0});
            this.barGraph3.Name = "barGraph3";
            this.barGraph3.Size = new System.Drawing.Size(25, 72);
            this.barGraph3.Value = new decimal(new int[] {
                        3,
                        0,
                        0,
                        0});
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.SystemColors.ControlLight;
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(27, 79);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(434, 230);
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.Red;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button1.ForeColor = System.Drawing.SystemColors.Control;
            this.button1.Location = new System.Drawing.Point(504, 39);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(115, 34);
            this.button1.Text = "Close Server";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.ControlLight;
            this.Controls.Add(this.button1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.barGraph3);
            this.Controls.Add(this.barGraph2);
            this.Controls.Add(this.barGraph1);
            this.Controls.Add(this.radioButton3);
            this.Controls.Add(this.radioButton2);
            this.Controls.Add(this.radioButton1);
            this.Controls.Add(this.rapidExecutionStatus1);
            this.Controls.Add(this.led1);
            this.Controls.Add(this.Solve);
            this.Text = "Hanoi Solver";
            this.Controls.SetChildIndex(this.Solve, 0);
            this.Controls.SetChildIndex(this.led1, 0);
            this.Controls.SetChildIndex(this.rapidExecutionStatus1, 0);
            this.Controls.SetChildIndex(this.radioButton1, 0);
            this.Controls.SetChildIndex(this.radioButton2, 0);
            this.Controls.SetChildIndex(this.radioButton3, 0);
            this.Controls.SetChildIndex(this.barGraph1, 0);
            this.Controls.SetChildIndex(this.barGraph2, 0);
            this.Controls.SetChildIndex(this.barGraph3, 0);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.Controls.SetChildIndex(this.button1, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void Solve_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalPulse
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/resolver"))).Pulse(200);
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in Solve_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void radioButton3_CheckedChanged(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["stackC"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Data/END_STACK").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in radioButton3_CheckedChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void radioButton2_CheckedChanged(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["stackB"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Data/END_STACK").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in radioButton2_CheckedChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void radioButton1_CheckedChanged(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["stackA"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Data/END_STACK").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in radioButton1_CheckedChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, this.button1_Click_Ack, "¿Desea realmente realizar esta acción?", "Warning", System.Windows.Forms.MessageBoxIcon.Exclamation, System.Windows.Forms.MessageBoxButtons.YesNo);
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click_Ack(object sender, ABB.Robotics.Tps.Windows.Forms.MessageBoxEventArgs e)
        {
            if ((e.DialogResult == System.Windows.Forms.DialogResult.Yes))
            {
                try
                {
                    // Calling RapidDataWrite
                    ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["true"];
                    ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Data/END").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
                    // Calling CloseScreen
                    this.CloseMe();
                }
                catch (System.Exception ex)
                {
                    ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click_Ack", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
                }
            }
        }
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // stackC
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable stackC = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("stackC", "3", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // stackB
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable stackB = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("stackB", "2", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // stackA
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable stackA = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("stackA", "1", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // true
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable @true = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("true", "True", typeof(ABB.Robotics.Controllers.RapidDomain.Bool));
                // 
                // Store variables
                // 
                services.ApplicationVariables.Add("stackC", stackC);
                services.ApplicationVariables.Add("stackB", stackB);
                services.ApplicationVariables.Add("stackA", stackA);
                services.ApplicationVariables.Add("true", @true);
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
